const stacks = [
  { name: 'JavaScript' },
  { name: 'TypeScript' },
  { name: 'Python' },
  { name: 'C#' },
  { name: 'Go' },
  { name: 'SQL' },
  { name: 'Node.js' },
  { name: 'React' },
  { name: 'React Native' },
  { name: 'Next.js' },
  { name: 'NestJS' },
  { name: '.NET' },
  { name: 'Django' },
  { name: 'FastAPI' },
  { name: 'Docker' },
  { name: 'AWS' },
  { name: 'Git' },
  { name: 'CI/CD' },
  { name: 'Github Actions' },
  { name: 'GitLab CI' },
  { name: 'TDD' },
  { name: 'Testes unitários' },
  { name: 'Testes de integração' },
  { name: 'Testes e2e' },
  { name: 'Jest' },
  { name: 'Cypress' },
  { name: 'Microsserviços' },
  { name: 'Clean Architecture' },
  { name: 'Design Patterns' },
  { name: 'SOLID Principles' },
  { name: 'Event-Driven Architecture' },
  { name: 'PostgreSQL' },
  { name: 'MongoDB' },
  { name: 'Redis' },
  { name: 'MySQL' },
  { name: 'Prometheus' },
  { name: 'Grafana' },
]

export { stacks }
